name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    # 8:00 AM IST every day (02:30 UTC)
    - cron: "30 02 * * *"
    # 7:30 AM IST every day (02:00 UTC)
    - cron: "00 02 * * *"
    # 11:30 AM IST Monday to Friday (06:00 UTC)
    - cron: "00 06 * * 1-5"

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '22'

      - name: Install Newman and Html-extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection with newman
        run: |
          newman run "Inwarranty-Flow-Collection Copy.postman_collection.json" \
            -e QA.postman_environment.json \
            -d createJobData.csv \
            -r cli,htmlextra \
            --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report
        if: always() # ensure that the archive executed irrespective whether the previous step has passed or not!
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html
      - name: Creating Github Page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_directory: newman/
      
